authors:
  kratoon:
    name: Ondrej Kratochvil
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/26163421?v=4
    url: https://github.com/kratoon
  hlinkavl:
    name: Vladimír Hlinka
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/184941608?v=4
    url: https://github.com/hlinkavl
  alzhli:
    name: Alžběta Hlinková
    description: Creator
    avatar: https://avatars.githubusercontent.com/u/215126208?v=4
    url: https://github.com/alzhli
